from __future__ import annotations

import json
from datetime import datetime
from typing import Any, Dict, List


def _section_line(section_counts: Dict[str, int]) -> str:
    ordered = [f"{name}:{count}" for name, count in section_counts.items() if count > 0]
    return ", ".join(ordered) if ordered else "none"


def build_markdown(
    digest: Dict[str, Any],
    generated_at: datetime,
    section_counts: Dict[str, int],
) -> str:
    summary = digest.get("daily_summary", "").strip()
    important_news: List[Dict[str, str]] = digest.get("important_news", [])
    key_takeaways: List[str] = digest.get("key_takeaways", [])
    model = digest.get("model", "unknown")

    lines = [
        "# AI Daily Digest",
        "",
        f"Date: {generated_at.strftime('%Y-%m-%d')}",
        f"Generated: {generated_at.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Model: {model}",
        f"Sections: {_section_line(section_counts)}",
        "",
        "---",
        "",
        "## TL;DR",
        "",
        summary or "No summary generated today.",
        "",
        "## Top Stories",
        "",
    ]

    if not important_news:
        lines.append("- No high-priority stories found today.")
    else:
        for idx, item in enumerate(important_news, start=1):
            title = item.get("title", "Untitled")
            brief = item.get("brief", "").strip()
            source = item.get("source", "").strip()
            link = item.get("link", "").strip()
            section = item.get("section", "").strip()
            lines.extend(
                [
                    f"### {idx}) {title}",
                    f"- Section: {section or 'other'}",
                    f"- Source: {source or 'Unknown'}",
                    f"- Link: {link or 'N/A'}",
                    f"- Why it matters: {brief or 'N/A'}",
                    "",
                ]
            )

    lines.extend(["## Key Takeaways", ""])
    if not key_takeaways:
        lines.append("- No clear takeaways today.")
    else:
        for point in key_takeaways:
            lines.append(f"- {point}")

    lines.extend(["", "---", "", "_Generated by ai-news-digest._", ""])
    return "\n".join(lines)


def build_text(
    digest: Dict[str, Any],
    generated_at: datetime,
    section_counts: Dict[str, int],
) -> str:
    summary = digest.get("daily_summary", "").strip()
    important_news: List[Dict[str, str]] = digest.get("important_news", [])
    key_takeaways: List[str] = digest.get("key_takeaways", [])
    model = digest.get("model", "unknown")

    lines = [
        "AI Daily Digest",
        f"Date: {generated_at.strftime('%Y-%m-%d')}",
        f"Generated: {generated_at.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Model: {model}",
        f"Sections: {_section_line(section_counts)}",
        "",
        "TL;DR",
        summary or "No summary generated today.",
        "",
        "Top Stories",
    ]

    if not important_news:
        lines.append("- No high-priority stories found today.")
    else:
        for idx, item in enumerate(important_news, start=1):
            lines.append(
                f"{idx}. [{item.get('section', 'other')}] {item.get('title', 'Untitled')} | "
                f"{item.get('source', 'Unknown')} | {item.get('link', 'N/A')}"
            )
            lines.append(f"   {item.get('brief', '')}")

    lines.extend(["", "Key Takeaways"])
    if not key_takeaways:
        lines.append("- No clear takeaways today.")
    else:
        lines.extend([f"- {point}" for point in key_takeaways])
    return "\n".join(lines) + "\n"


def build_json(
    digest: Dict[str, Any],
    generated_at: datetime,
    section_counts: Dict[str, int],
) -> str:
    payload = {
        "date": generated_at.strftime("%Y-%m-%d"),
        "generated_at": generated_at.strftime("%Y-%m-%d %H:%M:%S"),
        "section_counts": section_counts,
        "digest": digest,
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)
